# Generated by Django 3.2.1 on 2021-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
